# version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - PORT=5000
    volumes:
      - .:/app
      - data:/app/data

volumes:
  data:
